 &input1
 IDRUN = 23
 INDX =   9, NPX =   18432, NPXB = 0
 NTW = 1, NTV = 5
 NTP = 0, MODESXP = 41
 TEND = 500.000, DT =   0.0250, CI = 0.1
 VTX =   1.000, VTY =   1.000, VTZ = 1.000
 VX0 =   0.000, VY0 =   0.000, VZ0 =   0.000
 WMIN = 0.0; WMAX = 2.0, DW = 0.01
 NPLOT = 3
 /
 &input1b
 OMX = 0.0, OMY = 0.0, OMZ = 0.4
 NTA = 0, MODESXA = 41, NDA = 3
 NTET = 0, MODESXET = 41, NDET = 3
 NTAR = 5, MODESXAR = 41, NDAR = 3
 WRMIN = 0.0, WRMAX = 8.0, DWR = 0.01
 /
